name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: shivamgutgutia/bhashaxr:latest

    - name: Setup gcloud CLI
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCLOUD_AUTH }}
        project_id: bhasa-xr

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy bhashaxr \
          --image shivamgutgutia/bhashaxr:latest \
          --region asia-south1 \
          --project=bhasa-xr \
          && gcloud run services update-traffic bhashaxr --to-latest --region=asia-south1\
          --platform managed
